// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmeciakrvqiilfluctgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZWNpYWtydnFpaWxmbHVjdGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjgyNTIsImV4cCI6MjA2MzQwNDI1Mn0.B4El0nrJhySOiWJvitTTqCJPgP-5xqBIb1F2eMkk6uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);